"""Storage ports shared by the isolated reference and internal production profiles."""

from typing import Protocol
from uuid import UUID

from talk2data.domain.governance import GovernanceState
from talk2data.domain.runs import Conversation, RunEvent, RunRequest, RunSnapshot


class DefinitionJournal(Protocol):
    def seed(self, namespace: str, state: GovernanceState) -> None: ...
    def read(self, namespace: str) -> GovernanceState: ...
    def save(self, namespace: str, state: GovernanceState, expected: int) -> None: ...
    def delete(self, namespace: str) -> None: ...
    def close(self) -> None: ...


class ConversationJournal(Protocol):
    def create_conversation(self, owner: str, scope: str, identifier: UUID | None = None) -> Conversation: ...
    def conversation(self, owner: str, scope: str, identifier: UUID) -> Conversation: ...
    def conversations(self, owner: str, scope: str) -> list[Conversation]: ...
    def read(self, owner: str, scope: str, identifier: UUID) -> RunSnapshot: ...
    def runs(self, owner: str, scope: str, conversation_id: UUID) -> list[RunSnapshot]: ...
    def existing(self, owner: str, scope: str, request: RunRequest) -> RunSnapshot | None: ...
    def events(self, owner: str, scope: str, identifier: UUID, after: int) -> list[RunEvent]: ...
    def delete(self, owner: str, scope: str, identifier: UUID) -> None: ...


class RunController(Protocol):
    @property
    def store(self) -> ConversationJournal: ...
    def cancel(self, owner: str, scope: str, identifier: UUID) -> RunSnapshot: ...
